version: "3.7"

services:

  api_db:
    image: postgres
    container_name: pgsql_db
    environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=boredWebApp
    restart: always
    volumes:
        - database-data:/var/lib/postgresql/data/

  web_app:
    build:
        context: ..
        dockerfile: BoredWebApp/Dockerfile
    restart: always
    ports:
        - "80:80"
        - "443:443"

volumes:
    database-data: