name: Deploy Dotnet Service
on:
  push:
    branches:
      - master
  workflow_dispatch:
    
jobs:
  run-dotnet-service:
    runs-on: linode
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: set web app admin conn strings
        with: 
          files: '${{env.DOTNET_ROOT}}/BoredWebAppAdmin/appsettings.json'
        env: 
          ConnectionStrings.psqldb: ${{secrets.PSQLDB}}
          ConnectionStrings.wgadmin: ${{secrets.WGADMIN}}

      - name: set web app conn strings
        with: 
          files: '${{env.DOTNET_ROOT}}/BoredWebApp/appsettings.json'
        env: 
          ConnectionStrings.psqldb: ${{secrets.PSQLDB}}
          ConnectionStrings.wgadmin: ${{secrets.WGADMIN}}

      - name: docker compose
        run: |
          cd BoredWebApp
          docker-compose up --build -d

      - name: build api
        run: dotnet build AdminAPI

      - name: run dotnet from systemd
        run: |
          cp deployment/dotnetservice.service /lib/systemd/system/dotnetservice.service
          sudo systemctl daemon-reload
          sudo systemctl restart dotnetservice.service
          systemctl status dotnetservice.service