name: Deploy Dotnet Service
on:
  push:
    branches:
      - master
  workflow_dispatch:
    
jobs:
  run-dotnet-service:
    runs-on: linode
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: docker compose
        run: |
          cd BoredWebApp
          echo "psqldb=${{secrets.PSQLDB}}" > .env
          echo "wgadmin=${{secrets.WGADMIN}}" >> .env
          docker-compose up --build -d

      - name: build api
        run: dotnet build AdminAPI

      - name: run dotnet from systemd
        run: |
          cp deployment/dotnetservice.service /lib/systemd/system/dotnetservice.service
          echo "wgadmin=${{secrets.WGADMIN}}" > AdminAPI/.env
          sudo systemctl daemon-reload
          sudo systemctl restart dotnetservice.service
          systemctl status dotnetservice.service